services:
  - type: web
    name: twitter-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: xvfb-run -a python web_main.py
    envVars:
      - key: TZ
        value: Europe/Istanbul
